### ISSUE TITLE
The search does not work correctly

### ISSUE THREAD

**Issue by stetze88** [VShawn/PRemoteM#146]
**Describe the bug**
Unfortunately, the correct search results are usually not displayed. The search needs to be improved a bit.

**Expected behavior**
Correct search results. With a larger number of servers, it will otherwise be confusing.

**Screenshots**
![Screenshot 2021-08-13 104723](https://user-images.githubusercontent.com/73733823/129330854-3d2837b5-1521-456a-85a2-1b60defe50a2.jpg)

![InkedScreenshot 2021-08-13 104135_LI](https://user-images.githubusercontent.com/73733823/129331405-a64a0f88-ce25-450d-b6a3-27561a129012.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. Win11 Pro  21H1 22000.120]
 - PRemoteM Version [0.5.11.1]

**Comment by VShawn** [comment]
actually, the  `ts23` matched '**TS2**5:**3**389'
and 'ts23' will mathch all string contains ```T.....S......2....3.....``` if the `Discrete macher` is enabled.

![image](https://user-images.githubusercontent.com/10143738/129431342-92fe9d4f-9e88-4065-a3a3-ce27642dfe38.png)

Since you have so many servers in the app, it is recommended to disabled the  `Discrete macher`


![image](https://user-images.githubusercontent.com/10143738/129431311-6d82e7b3-92f7-4689-84ee-1a17b7325e55.png)


And then, it works.

![image](https://user-images.githubusercontent.com/10143738/129431357-18156f61-38b3-4cc4-bda6-ebe0f3a3eb7c.png)

**Comment by stetze88** [comment]
Much better. Thank you.
