### ISSUE TITLE
Using configuration on remote share

### ISSUE THREAD

**Issue by gofastgirl** [VShawn/PRemoteM#149]
Hi,
Some I'm trying to do a configuration, but PRemoteM is not happy.
I have 3 different client machines that I use to connect to various VMs via RDP only.
So I put all PRemoteM files onto a shared drive that all guests can access.
I configured PRemoteM to connect to a couple of my VMS.
I configured PremoteM to store it's database in the same folder as the executable.
I added permissions to the ini and db files for EVERYONE Full Access
But I keep getting errors. 
Database: Permission denied for reading! Please check your password of file occupation.

Any ideas what I need to do to get this to work?
Thanks!

**Comment by VShawn** [comment]
>Database: Permission denied for reading! Please check your password of file occupation.

Since we open the database in exclusive mode,  our PRemoteM database can not be shared by two client. 

You can make a copy of PRemoteM in each of your gustes, and let them use their individual database. You have to export/import data manually when you change your connection info.

---

About the data sharing/sync, you can take a look at this ticket, I think sharing sqlite database will alway cause conflicts, so I hope I can add mysql support or C/S structure support, then we can get a central data source, and all the client can read data from the same source.

https://github.com/VShawn/PRemoteM/issues/76
