### ISSUE TITLE
Select Monitor in MultiMonitor Support

### ISSUE THREAD

**Issue by AnTri** [VShawn/PRemoteM#153]
Hi,

is it possible to specify the monitors for the rdp session? I can only select "All Screens". In a .rpd file I can use "selectedmonitors:s:1,2" to select the monitors to display the RDP session.

Thanks

AnTri

**Comment by AnTri** [comment]
Sorry I can't remove the "bug" label...

**Comment by VShawn** [comment]
Hi @AnTri in next version, PRM will allow you to customize rdp file options. So that the `selectedmonitors:s` can be set.

![image](https://user-images.githubusercontent.com/10143738/143599699-00219e83-e44b-41f5-b0f5-729be34b1037.png)


Sorry for the slowly approach, I just too busy on work these days.

**Comment by VShawn** [comment]
@AnTri hi, [here](https://github.com/VShawn/PRemoteM/releases/tag/0.6.0-beta) is our new beta release, try it to edit the rdp file template to select monitors.
