### ISSUE TITLE
Kitty

### ISSUE THREAD

**Issue by tj57** [VShawn/PRemoteM#21]
Good job, thank you for quality and effort.

Would it be possible to embed Kitty portable in PRemoteM ? Kitty portable http://www.9bis.net/kitty/ can store sessions in ini files.
Could you create new group kitty with imported all sessions from ini files or only embed kitty with external configuration. 
What do you think about it ?

**Comment by VShawn** [comment]
sorry for forgot to check your issue.

i dont know if KiTTY can start with cmd + parameters to open a new session? PRmoteM can embed KiTTY only  If cmd + parameters works.

maybe i would first add a button to import KiTTY ini config to PRemote config format, so that users can migra from  KiTTY easier. then I need some document of how to deserialize the KiTTY ini file, could you give me some?

**Comment by VShawn** [comment]
@tj57 
KiTTY is available in the latest release: https://github.com/VShawn/PRemoteM/releases/tag/0.5.1.2011110905
