### ISSUE TITLE
PremoteM user profile

### ISSUE THREAD

**Issue by 1d01t** [VShawn/PRemoteM#223]
Hi,
first of all i really love your project! Thanks a lot for your excellent work.

former we tried using PRemoteM "0.5.10.2" in our enterprise environment.
It worked pretty well. We installed the software to "c:\Program Files" and the
user profile automatically was created at the userspace: "AppData\roaming\premotem\"

Now in the actual version "0.6.2.2" the user profile seems broken.
When we try to open PRemoteM now it says "We don't have write permissions for the 
C:\Program Files\premotem\PRemoteM.json file!"
![PRemotem-error](https://user-images.githubusercontent.com/67950721/159896594-79ed94a9-d9f8-4845-81d4-625c3cb1a8d6.jpg)

Also PRemoteM couldn't find the premotem.db at: "AppData\roaming\premotem\" automatically.
Instead it tried to build a new one at: "C:\Program Files\premotem".

Our client users never have write permission on "C:\Program Files".

Is it intended to give write permissions to the whole "C:\Program Files\premotem" directory?
it would be nice to have the functionality back, to store user content to the userspace again.
Would that be possible?

**Comment by VShawn** [comment]
In 0.6.X, I set the default path of the configuration file to the folder path of the exe. So that our user can put PRemoteM in their portable device and take it to anywhere.

> Our client users never have write permission on "C:\Program Files".

Since your client  have no write permission on "C:\Program Files". You can put PRemoteM to an writable  folder.

> Also PRemoteM couldn't find the premotem.db at: "AppData\roaming\premotem" automatically. Instead it tried to build a new one at: "C:\Program Files\premotem".

I did have some code for the 0.5 upgrade to 0.6 in 
https://github.com/VShawn/PRemoteM/blob/0.6.1.1_fix/PRM.Core/Service/ConfigurationService.cs#L172-L186

Maybe your permission broken the procedure.
I'm not sure about that, I never thought about the low-privileged user in the enterprise environment, so I've never trested your situation. Sorry about that.


But You can rest assured that your data will not be lost. 
Do it manually by to find your data back:
1. move old db file to the path in the `PRemoteM.json`
2. or you can modify the `PRemoteM.json`, set the field `SqliteDatabasePath` to your old path.
3. or re-install `0.5.10.2` and export all data to json, and import them into `0.6.2`

**Comment by majkinetor** [comment]
This is not correct behavior of PRM if it is desired to work in multiuser environment. The point is to have system install, and that each user has its own db & config file. 

For that too work, installation must take into account this - by default it should work in non-portable mode, which means that app is installed in standard location, and user data is in their AppData folder and in portable mode, app uses config and db from local directory. Some tools do this via registry setting, some via command line parameter, and some via special file in app folder (mere existence marks the portable mode, FooBar2000 works like this for example).

I think PRM should go the last variant, if file is there, it should work in portable mode, if file is not there (default) it should work in multiuser mode.

**Comment by VShawn** [comment]
sounds reasonable

I can add a "portable version" option to `guidance`, which automatically creates a flag file if the user checks it.

**Comment by majkinetor** [comment]
I should also add portable mode param to choco package when this is finished and released.

**Comment by VShawn** [comment]
@majkinetor 

I didn't make a special file to target the app run on portable mode

instead, if the profile existed in the exe folder PRM will run on portable mode.

![image](https://user-images.githubusercontent.com/10143738/167616070-81318097-84b1-4d79-84a2-ffe03586446e.png)

this option will decide will the profile would be created when a user open PRM for first time.

Will these changes affect you ` add portable mode param to choco package `?

**Comment by VShawn** [comment]
![image](https://user-images.githubusercontent.com/10143738/167627183-dfb3c15e-3ae4-4b79-bdbb-2401cc7a9002.png)

A butter ui

**Comment by majkinetor** [comment]
This means that you can't install it in portable mode, but can only later switch to it. I don't think this is going to work very well without option that can be passed during installation. You should either provide some install parameter for this, or have some other mechanism.

> if the profile existed in the exe folder PRM will run on portable mode

What counts as profile? Database location only? In that case, installer could create dummy SQLite file just like I suggested, its just different file. This file probably can't be empty, so package installer must include empty db generated by PRM which is not great as it is subject to change in the future - when you add new stuff to db, unless PRM can automigrate it during first run, it may crash. If completely empty db file works, we can use that instead some other file.

**Comment by majkinetor** [comment]
Ah, I see now that you first show this popup on first use, so this might actually work. To me this also seem unfriendly to automated installers because basically part of the installation procedure is manual and hence it is error prone - imagine I install this corporate wise, and for all users to behave the same. Some users will then on the first run choose one option and some other. Yes, they can change it later anyway, but they might not bother, while here you impose this.

Not sure. 

Maybe give it a go, and we can revise it later depending on the feedback.

**Comment by VShawn** [comment]
Maybe I can make a trick for you and those enterprise installation. I can make PRM force into portable mode when there is a file named  `FORCE_INTO_PORTABLE_MODE`, and force into AppData mode when the file `FORCE_INTO_APPDATA_MODE`.

**Comment by 1d01t** [comment]
Most installers in the wild have the ability to deliver parameter with them by execution. For example we can install google chrome by CMD command: ```chrome_installer.exe /silent /install``` so the installer will not ask anything to the user. It could also be possible to add a parameter ```/portable``` or ```/enterprice``` or so, to enable an easy automated installation in enterprice environments. Would that be possible?

**Comment by majkinetor** [comment]
We don't need 2 files, just one :) Its either portable or not :)

**Comment by VShawn** [comment]
> We don't need 2 files, just one :) Its either portable or not :)

I wish to keep the portable option for first time use, that's why I think there are two flag files.

- Personal user who download from GitHub release can choose portable or not when  first time use.
- A choco user with portable parameter will get a PRM package with flag file `FORCE_INTO_PORTABLE_MODE` then the `portable option for first time use` will be disabled.
- A choco user without portable parameter will get PRM without any flag file.
- A sysadmin may deploy PRM with file `FORCE_INTO_APPDATA_MODE` to his office computers


@1d01t 

I think command arguments are not intuitive(or forgettable), so I choise a flag file. 

In my approach what sysadmin need to do is deploy PRM with file `FORCE_INTO_APPDATA_MODE ` to client machines, then PRM will write profile into APPDATA. I think this can meet your demand.

![image](https://user-images.githubusercontent.com/10143738/167885914-ef72bc34-ea30-4993-a294-4cf82dba2972.png)



As the opposite, with CMD command, sysadmin have to disallow client machine `double-click exe to start the PRM` and make a clear shutcut `c:/blabal/premotem.exe -enterprice` on every client's desk.  Higher aintenance costs.

**Comment by VShawn** [comment]
![image](https://user-images.githubusercontent.com/10143738/168257172-73d21041-b394-44eb-b462-c0fa8a4fff34.png)

**Comment by majkinetor** [comment]
Its not obvious from the app if it runs in portable mode or not. Its probably good to make this info available in About box or something.
