### ISSUE TITLE
Separate by Group (Separar por Grupo)

### ISSUE THREAD

**Issue by profbaco** [VShawn/PRemoteM#46]
On Linux I work with the Remmina program (I think you should know about it). He works the same way you do, which are the connection groups.
But he has a view where I can see the list of connections grouped by group - like a folder.
This latest version that you released I can see them in a list - I thought it was fantastic. But is there a possibility to group them by folders, where these folders are the connection groups?
============================
No linux eu trabalho com o programa Remmina (acho que você deve conhecê-lo). Ele trabalha com mesmo jeito que você, que são os grupos de conexões.
Mas ele tem uma visão onde eu consigo ver a listagem de conexões agrupas por grupo - tipo uma pasta.
Esta ultima versão que vc soltou eu consigo ver eles em forma de lista - achei fantástico. Mas existe a possibilidade de se agrupar eles por pastas, onde estas pastas são os grupos de conexão?

![Groups](https://user-images.githubusercontent.com/5287317/103152378-0b7e6080-4766-11eb-8903-45eecfcd87f9.png)

**Comment by majkinetor** [comment]
This is already possible in premotem its just that interface is different. I personally like it better then folders.

![image](https://user-images.githubusercontent.com/85767/103152425-1a760a80-4788-11eb-9a4b-ae0ba777ec95.png)

**Comment by VShawn** [comment]
I see,  the advantage of 'folder view' is that users can clearly see belonging of group.
I will check out if it is possible to add a group name in server info list view when list view is order by Group, and let it fold/unfold when click the group name.

Since this feature is not important and seems to be difficult to implement on current list view, I would not devote a lot of time on it. so don't expect too much.

**Comment by VShawn** [comment]
something like this, it seems only work with UWP since PRemoteM is based on WPF.

![image](https://user-images.githubusercontent.com/10143738/103165931-9c356900-4858-11eb-9e47-1bc5c7d0ee3a.png)

**Comment by majkinetor** [comment]
Why just not add new csortable column Group in _All_ view that achieves the same effect ?

**Comment by VShawn** [comment]
> Why just not add new csortable column Group in _All_ view that achieves the same effect ?

sorry but I don't take what you mean, do you have a demo for it?

**Comment by majkinetor** [comment]
Sorry, didn't notice it, but the column exists already. 

So, I don't think the proposed feature is useful at all at this moment - it doesn't bring anything new to the table and requires implementation and maintenance. 

This would perhaps be useful if you allowed groups within groups (but even then sorting the column would achieve teh same effect if it would contain entire path instead of just leaf group).

**Comment by majkinetor** [comment]
> But he has a view where I can see the list of connections grouped by group - like a folder.

![image](https://user-images.githubusercontent.com/85767/103173253-fd117100-4859-11eb-84e2-cf2101293924.png)

Typing group name in search doesn't limit it, but you have tabs already.

**Comment by majkinetor** [comment]
You only can't achieve the following with tree view: see M < N of your total groups at the same time. Not sure if that is useful at all.

**Comment by VShawn** [comment]
@majkinetor 

yeap, that‘s why i treat it as not important feature.

> Since this feature is not important and seems to be difficult to implement on current list view, I would not devote a lot of time on it. so don't expect too much.

---
BTW, your screenshot blur effect was just cool! how do you did that?

**Comment by majkinetor** [comment]
> BTW, your screenshot blur effect was just cool! how do you did that?

Paint.net and its radial blur effect.
