### ISSUE TITLE
Connecting to VNC error: value does not fall within expected range

### ISSUE THREAD

**Issue by arcana261** [VShawn/PRemoteM#54]
**Describe the bug**
When I try to connect to remote VNC server, I get this error.

**To Reproduce**
1. Start a virtual VNC server in Linux using command `x11vnc -create -listen 0.0.0.0 -env PATH="$PATH" -env FD_PROG=/usr/bin/fluxbox -env X11VNC_FINDDISPLAY_ALWAYS_FAILS=1 -env X11VNC_CREATE_GEOM=${1:-1920x1080x16} -gone 'killall Xvfb' -bg -nopw` done in Ubuntu 20.04
2. Connect to VNC server

**Expected behavior**
Connect to remote VNC server

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Win10 Home]
 - PRemoteM Version [e.g. 0.5.7.2101041110]

**Additional context**

**Comment by VShawn** [comment]
sorry, I tested VNC via TightVNC on windows when I developeded, and it work properly for me.

![image](https://user-images.githubusercontent.com/10143738/104080422-bdd41e80-5262-11eb-9a65-8cfc5869d9ad.png)

No much test was run on Linux because I don't have a Linux OS with desktop to test it. But I prefer **[xrdp](http://xrdp.org/)** butter Xthen VNC if I need a desktop environment one day. In fact I add VNC protocol just in case.
😕 

## Note that PRemoteM was based on VNCSharp, it is archived and not support VNC4 or higher(RFB protocol over 3.8 are proprietary).

some discussions about this:
https://github.com/mRemoteNG/mRemoteNG/issues/494

**Comment by VShawn** [comment]
# update
Tested on Ubuntu18 LTS via x11vnc by 
`
 x11vnc -auth guess -rfbauth /etc/x11vnc.pass -rfbport 5900 -forever -display :1
`

![image](https://user-images.githubusercontent.com/10143738/104080849-7ef39800-5265-11eb-851c-e30f1e9d3ceb.png)

**Comment by arcana261** [comment]
Thank you for your reply!
Here is the screenshot:

![image](https://user-images.githubusercontent.com/10746709/104081738-792b9180-5228-11eb-861d-1c5459eb4c89.png)

**Comment by arcana261** [comment]
It might also help that I've run x11vnc under WSL.. But I don't expect VNC to fail because of this.. other tools work just fine..

**Comment by VShawn** [comment]
it is not a VNC protocol fault, but a value verification fault, can you show me your address info? 

or it is best for me to send me your config file to my email if it can be shown to me.
![image](https://user-images.githubusercontent.com/10143738/104084761-e836d380-5284-11eb-94fb-9afeee5a5895.png)

**Comment by VShawn** [comment]
close: no further report for long and can't reproduce this bug.
