### ISSUE TITLE
Exiting SSH connection should close its window/tab

### ISSUE THREAD

**Issue by majkinetor** [VShawn/PRemoteM#57]
When I exit the shell, I am left with the dummy black window that I need to explicitly close as no other action could be done on it. This is not a big problem per se, but certainly UX fail.

If it is possible to detect this, you should close the hosting window automatically.

**Comment by VShawn** [comment]
> I am left with the dummy black window

sorry? I dont get how you left dummy black window? Did you mean left with 'exit' command instead of click 'X' button on windows top right?

> If it is possible to detect this

And actually yes, we can do thay. Since we cannot get Shell close event without pipe\FIFO\signal(I am not intend to  implemt any communication between processes). We can still create a background watcher to check if KiTTY process is alive periodically. Onec KiTTY was killed we can close the tab.

**Comment by majkinetor** [comment]
![p](https://user-images.githubusercontent.com/85767/104444095-9ac5a980-5597-11eb-92fc-2609dfc0b930.gif)

**Comment by VShawn** [comment]
ahh, that‘s exactly what i mean.

BTW your address/username was shown in the GIF, it's butter to delete it.

**Comment by VShawn** [comment]
found something useful 

![image](https://user-images.githubusercontent.com/10143738/104448158-c2d4fd00-55d7-11eb-8b5f-51a63b5583b5.png)

**Comment by VShawn** [comment]
works

![1](https://user-images.githubusercontent.com/10143738/104449536-b5b90d80-55d9-11eb-953f-b70ee1d2389e.gif)
