### ISSUE TITLE
Unhandled error when opening connection - UCEERR_RENDERTHREADFAILURE

### ISSUE THREAD

**Issue by Shooshka** [VShawn/PRemoteM#70]
**Describe the bug**
Error when open new connection.

**To Reproduce**
See this error only once

**Screenshots**
![2021-01-29_07-51-50](https://user-images.githubusercontent.com/1889052/106243414-6c440180-621a-11eb-9f68-73497a0de63d.png)

**Desktop (please complete the following information):**
Win 10 20H2
PremoteM 0.5.8.2101192131

**Comment by VShawn** [comment]
Thanks for your report! 

according the discussions on SNS

https://social.msdn.microsoft.com/Forums/sqlserver/en-US/d4f943eb-630e-48ac-a8f8-00e539bb7856/wpf-crashes-with-error-hresult-0x88980406-at?forum=wpf
https://github.com/dotnet/core/issues/1995
https://github.com/dotnet/wpf/issues/3100


it may be a bug of WFP render thread. It is said it was fixed in .net framework 4.0+, but it still some reports even after net core 3.0.

I am not very sure if this bug caused your issue, but it may be helpful if you can upload your log file like `PRemoteM.log_2021XXXX.md` in `C:\Users\XXX\AppData\Roaming\PRemoteM`. Please mind you dont need upload full log file, just paste the `Fatal` info would be enought.

**Comment by Shooshka** [comment]
Will be no problem if logs have some "Fatal" in them but...

![2021-01-29_12-18-20](https://user-images.githubusercontent.com/1889052/106256274-1c6e3600-622c-11eb-935b-03c1e3406ba3.png)

From day with error have only 1 string:
2021-01-28T01:02:47.4567714+03:00[ThreadId:0000000001]		<font color=Green>Debug</font>		RDP Host:  RdpOnOnLoginComplete
