### ISSUE TITLE
Port from .NET Framework to .NET 6

### ISSUE THREAD

**Issue by majkinetor** [VShawn/PRemoteM#72]
App should be ported to .NET 5 as it is the only version of net moving forward.

Split from #26

**Comment by VShawn** [comment]
# find it maybe not a very good  timeing for Desktop application with .NET 5.

I build a .NET 5 based application for test recently, coding is smooth with, Net5, but the deployment is stuck, and I dont see much benefits on UI or UX with Net5 now.


## environment install

|Version| built-in| support win10|
|---|--|--|
|[.net framework 4.8](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/versions-and-dependencies)|win10 1903 and above| win10 1607 and above|
|.net 5 | none built-in | win10 1607 and above|


since .net 5 was not built-in in any win10 version, our user have to install .net 5 runtime themselves, while our current version with .net framework 4.8 most people can run app without any runtime installation.

I test my new test .net5 app on my workmate‘s companies, none of them can run directly. Double click the exe, nothing happen,no window shows no runtime error report.

while .net framework4.7 application run on none-4.7-runtime machine:
![image](https://user-images.githubusercontent.com/10143738/109097595-9a096100-775a-11eb-9f87-c878032e7939.png)





## self-contained deployment mode.

![image](https://user-images.githubusercontent.com/10143738/109095302-69272d00-7756-11eb-8488-6fd6795de5d5.png)

in this mode, app will built-in .net5 runtime, this works on my workmate‘s companies, only the app become huge: 

2MB -> 132MB

which means our user may have to dowload a huge package in this deployment mode, the single 


![image](https://user-images.githubusercontent.com/10143738/109095614-126e2300-7757-11eb-9f16-ac81386cd6d6.png)

### Microsoft Store

not test yet, doubt how they fix the runtime problem.

**Comment by majkinetor** [comment]
Sounds reasonable. 

> coding is smooth

Coding speed is one of the major benefits and attraction of new contributors. Its not everything about end users. Not sure if that is one of your goals tho.

> user have to install .net 5 runtime themselves

Yeah they do, once. 100MB+ is something you get when you include entire framework, however you can cherry pick parts of it to reduce it. Also, even if PRM brings dotNet framework with itself, it could do it only once so updates will be fast. 

Downloading 100MB is not big deal nowdays, many apps are in that range, particularly electron apps that bring entire browser with itself.

Old framework is dead technology too.

Be all that as it is, you might be right, that timing is not good. However, I think you should at least not use any library that doesn't have .NET5 version because once when all those problems go away, you will have much easier time switching over...

**Comment by VShawn** [comment]
> I think you should at least not use any library that doesn't have .NET5 version because once when all those problems go away, you will have much easier time switching over...

this has been taken into consideration since PRM was 0.01. In all libaray I used, Dragablz is the only one that does not support .net core https://github.com/ButchersBoy/Dragablz/issues/231. expecting Dragablz update or find a replacement library.

**Comment by majkinetor** [comment]
There is a fork for Drabalz that supports it.

**Comment by VShawn** [comment]
https://github.com/miroiu/Dragablz? this fork has been deleted

**Comment by majkinetor** [comment]
https://www.nuget.org/packages/Dragablz.NetCore/

**Comment by majkinetor** [comment]
Ah, its unlisted.... ignore

**Comment by VShawn** [comment]
> Double click the exe, nothing happen,no window shows no runtime error repor

it was shown when running on my win server 2019

![image](https://user-images.githubusercontent.com/10143738/109242994-16617a00-7817-11eb-9274-f74848698e2e.png)

**Comment by majkinetor** [comment]
FYI, there is no plan to include .NET5 distribution in the Windows out of the box:

* https://github.com/dotnet/core/issues/4600

**Comment by VShawn** [comment]
.net 6 lts is released now.

**Comment by VShawn** [comment]
it is done !

**Comment by majkinetor** [comment]
Ooo.. awesome.
