### ISSUE TITLE
Option to specify connection defaults 

### ISSUE THREAD

**Issue by majkinetor** [VShawn/PRemoteM#73]
This is split from #26 Default username/password for protocol. I abstracted this to allow setting any option, if that is too much feel free to revert to original idea.

This would allow setting up default for protocol (and perhaps group) so that when connection using that protocol is created, it uses defaults if specified.  For example, I might want to set full screen RDP as default, or default icon or resources  or default color. This requires more work then original username/password idea for sure, but not too much, and original idea is highly limited in scope (what If I want SSH default key ?)

This is next to template as it only requires a name for it to be added. In this scenario user can create N templates for protocol and mark one as default, while others are available to use. Probably overkill IMO, but implementation is trivial with above in place.

**Comment by majkinetor** [comment]
This can be easily solved by adding new button to config editor "Use current options as default for future connections". This is trivial to add and reuses the existing interface for setup.

Scenario: I want to change RDP defaults

1. I add new connection and go to RDP tab
2. Set options I like, remove options I don't like
3. Click the "Use current options as default for future connections" button/option 
4. Close the config editor without saving anything

I can repeat this on other protocols.

**Comment by VShawn** [comment]
>  "Use current options as default for future connections"

this is exactly what i think

**Comment by rbreaves** [comment]
Default screen resolutions, which monitors to open up on. Also due to wanting to activate hidden taskbars the 2 pixel border of the window (even when not fullscreened, but simply maximized) should be removed on all sides. What is tricky though is if the user wants to activate both their local taskbar and the remote taskbar (assuming they are located on different sides).

I carefully size my remote window so I can do both, but it is annoying to setup. (local taskbar at bottom, so 1 pixel gap is left, and the remote taskbar is on the left or right.)

Devolutions RDM is less annoying to deal with because it allows me to dial in the exact dimensions I need when it opens. (it is slow as molasses starting up though)

**Comment by VShawn** [comment]
@rbreaves Hi, this is basicly my personal taste. I'd like to have same border to indicate border of the session for me. 

of couse the border can be removed, I just want consider the approach to satisfy both of us


for now, you can try this build.

[0.6.0-beta2 TmpRelease.zip](https://github.com/VShawn/PRemoteM/files/7766039/0.6.0-beta2.TmpRelease.zip)

![image](https://user-images.githubusercontent.com/10143738/147172605-9e2062b5-7503-464d-8a93-00c6994da3e0.png)

**Comment by rbreaves** [comment]
I do like the thinner border for sure! I am wondering if  it would possible to get rid of all decorations and tabs for an RDP window as well. Have that as an option? I actually have use cases where xfreerdp is prefect, but the wfreerdp build on windows is unstable.

I know Remmina on Linux has an option to hide all toolbar like options as well as hide the tab bar if your only dealing with one session (but also an option to open all additional sessions in separate Windows if that is desired). I think Linux users may be more apt to use Workspace/Virtual desktops so that may be why Remmina supports that as well.

**Comment by VShawn** [comment]
Do we still need a template system?

**Comment by majkinetor** [comment]
This is not template system, but system for defaults, originally created as extension of username and password default setup.

Bulk connection setup and this has nothing to do with each other - first is to setup bunch of connections, the second is to minimize work on every new connection.

Benefit of this functionality is there, but it depends on how much connections you create. There are no hundreds of options now in connections but only around 10, most of which could be ignored. 

So I think we can move this to Limbo or close it.

**Comment by VShawn** [comment]
> username and password default setup.

I've always felt that `duplicate` can play the role of the template, so few benefit can get from making new feature `username and password default setup`

**Comment by majkinetor** [comment]
Yeah, you are right, I totally forgot about it and I even designed other apps that use exactly the same mechanism - tags and duplication. You mark templates with specific tag, like `#template`, and then duplicate it. The negative side is that you have to remove tag from the copy. The positive side is that you can duplicate multiple templates.

I will hence close this.
