### ISSUE TITLE
Putty low-level calls

### ISSUE THREAD

**Issue by shuncon** [VShawn/PRemoteM#80]
If I use Putty for low-level calls, I was dissuaded, and the rz/sz upload and download commands won’t work.

**Comment by VShawn** [comment]
Hello, currently PRemoteM using the official KiTTY, so if function you said is supported by KiTTY, then this issue should be caused  by KiTTY configuration.

Since I am not familiar with this, it will be a great help to:

- offering info of how to set up `putty low-level calls` environment
- and how to set up rz/sz upload/download(I use sFTP myself).

**Comment by VShawn** [comment]
close by: `no further information`
