### ISSUE TITLE
Credential store that can be referenced by connections

### ISSUE THREAD

**Issue by d0pang** [VShawn/PRemoteM#89]
能不能把账号密码放到配置界面管理, 可以配置多个账号密码, 然后在服务器配置的时候只需要选择使用哪个账号就好. 
因为我们大部分用的都是同一个账号, 而账号的密码在企业一般是要定期修改的, 这样每次修改就方便多了.

**Comment by majkinetor** [comment]
English please ?

**Comment by d0pang** [comment]
Can you move account and password into the configuration page for management? 
User can configure multiple account and password, and then we only need to select which account to use when configuring the server info.

Because most of us use the same account, and the password of the account is usually modified regularly in the enterprise, so it is much more convenient to modify each time.

**Comment by majkinetor** [comment]
Thanks @d0pang .

> Can you move account and password into the configuration page for management?

Moving is definitely not good option as some connections are coupled to credentials.

> Because most of us use the same account, and the password of the account is usually modified regularly in the enterprise, so it is much more convenient to modify each time.

I see, so this can be solved via several different ways, one of which is mass editing accompanied with good filtering capabilities - you could for example select all connections using specific username and mass edit the password. The speed up is about the same as in separated credentials list and functionality is way more useful. This is proposed already somewhere... I'll have to create a ticket for it, can't find it.

One problem with credential list is that it can later have a lot of stale credentials which can then be maybe security and/or usability issue. You also might not know what you are affecting so we need separate UI to show you what connections use it so this already starts to look like good filtering on list and mass editing.

**Comment by VShawn** [comment]
这是个很棒的想法，之前也有人提及了此需求，我们也一直在考虑，但却一直没能决定往哪个方向去做。在我看来，分开存储账号和连接信息确实有利于大批量的服务器管理，但同时也会带来软件操作体验的恶化：用户添加一个服务器时不得不先去一个界面新增账号，再去另一个界面添加IP、端口信息。这对于那些“个人”用户来说（比如说我自己）会使新增服务器的操作步骤翻倍，由于这个软件定位首先是 “Personal”, 所以我认为得首先照顾到少量服务器添加/修改的便利性。

目前我的想法是：

- 思路A：提供批量修改功能，不提供账号密码单独配置。
- 思路B：提供账号密码单独配置，但同时也要支持独立账号密码。

目前的开发是按照思路A展开的。


-----

It's a great idea, we have been considering it for long, but not beed decided how to support this yet. IMO, the separate storage of account and connection information is indeed conducive to large-scale server management, but at the same time it will also bring the deterioration of the software experience: when users add a server, they have to go to one page to add an account, and then to another page to add IP/port information. For those "personal" users (for example, myself), the operation steps of adding a new server will be doubled. Since this software is mainly pointing on "Personal" use, I think the convenience of adding a small number of servers must be taken care of first..

My current thoughts:

-Idea A: Provide batch modification function, do not provide separate account and password configuration.
-Idea B: Provide separate account and password configuration, but also support independent account password.

The current development following by idea A.



-----

目前你可以通过以下步骤进行账号密码的批量修改

At present, you can edit account/passwords by following steps

1. Firts you can create a connection copy var `duplicate`

![image](https://user-images.githubusercontent.com/10143738/108930325-b507a280-7680-11eb-86a1-3b995cd2f9b4.png)

2. You can change multiple connections credentials via `Edit selected`

![image](https://user-images.githubusercontent.com/10143738/108930572-20517480-7681-11eb-9367-e623b3e83f3d.png)

**Comment by VShawn** [comment]
# About Idea B

This idea needs a lot of code change and database change, and brings issues like @majkinetor mentioned above. 

> One problem with credential list is that it can later have a lot of stale credentials which can then be maybe security and/or usability issue. 

I don't like idea B, just for sharing the idea.

## UI
UI might look like:

![image](https://user-images.githubusercontent.com/10143738/108931819-46781400-7683-11eb-9223-deb209b26ea0.png)

- individual

   when user add connection with an individual credential, he select the `individual` tab, and the form will be same with the current version.

-  unify
   When user choose unify tab, he can select a credential from sotrage.

## Credential

- auto add
  credential would be able auto save as `unify credential` when a `individual credential connection` was saved.

- auto delete
  when all connections refer to the `unify credential` were deleted, then the `unify credential` will be auto deleted.
  
- add/edit in setting page.
  need offering a page to manage `unify credential`

**Comment by majkinetor** [comment]
All this can be done without changing one bit of UI or habit. I hurry now but will get back to this soon.

**Comment by d0pang** [comment]
Thank you for your reply. I think both solutions are good and can solve my problems.

**Comment by VShawn** [comment]
@d0pang  now we will offer a more powerful bulk editor, see #83
