### ISSUE TITLE
Keyboard enter key is not functioning in vnc

### ISSUE THREAD

**Issue by shawhu** [VShawn/PRemoteM#96]
**Describe the bug**
keyboard enter key is not functioning in vnc connections (tightvnc server)

**To Reproduce**
1. download and install tightvnc service on a windows 10 machine
2. connect
3. open a notepad and try the enter key
4. it doesn't work

**Expected behavior**
enter key should work

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10 Pro, latest version with all the updates
 - PRemoteM Version0.5.8.2101282043

**Additional context**

**Comment by VShawn** [comment]
thanks for reporting, You can use RDP/XRDP as a temporary solution.

---

I confirmed this bug. <kbd>enter key</kbd> did work with mRemoteNG via VNC(using VncSharp), but  PRM is a WPF app, so I setup a minimum demo to test **VncSharpWpf** then, <kbd>enter key</kbd> not work .

So the bug was produced  due to the lib [VNCSharpWPF](https://github.com/nakano531/VncSharpWpf). 

![image](https://user-images.githubusercontent.com/10143738/111279506-ba4f8000-8675-11eb-99b3-b9d4bc6b95e8.png)

Since the VncSharpWpf was archived, we may have to find a replacement lib for VNC.
